[env:esp32-s3-devkitc-1zz]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; for sparkfun lib doesn't help -> lib_ldf_mode = deep+

; to  fix not-reboot problem
; no good .....    board_build.usb_cdc_on_boot = 1

; // copilot: "debug esp32s3 platformio vscode"
; // wont work because platformio uses python3 and debug python2.7 ...
; upload_protocol = esp-builtin ; Tells PlatformIO to use the ESP32‑S3’s internal USB‑JTAG.
; debug_tool = esp-builtin ;Ensures flashing also uses the same USB interface
; debug_init_break = tbreak setup ; Breaks at the start of setup().

; “Look inside this folder for subfolders with
; folder named src containing c++/.h files”
lib_extra_dirs = 
    ;lib/downloadLibs/QMC5883P    ; magnetometer
    ;lib/downloadLibs/QMI8658C    ; gyro/accelerometer
    ;lib/downloadLibs/sensorFus/dnload/MadgwickAHRS   ; also works ok
    ; put sparkfun in lib_deps instead .. C, C++ mixed breaks linker if here
    ; lib/downloadLibs/MCU20948/sparkfun_dnload/SparkFunICM20948 ; /src/ICM_20948.h
    ; lib/downloadLibs/MCU20948/sparkfun_dnload/SparkFunICM20948/util ; "util" folder too
    lib/myLib
    ; with below, need path for subdir #include <ble_rtos/BleHelper.h>
    lib/myLib/helpers ; need new entry because of additional level
 build_src_filter =
    +<./>
    +<../lib/myLib/helpers/ble_rtos/*.cpp> ; wont descend into dir by default
    ; exclude examples from this downloaded library so they dont get compiled into other stuff
    -<lib/**/examples/>
    -<**/*skipCompile*/> ; alternate versions of tests produce duplicates/errors
; Use NimBLE library - much more reliable than ESP32_BLE_Arduino
lib_deps = 
    https://github.com/h2zero/NimBLE-Arduino.git#1.4.1
    adafruit/Adafruit NeoPixel @ ^1.12.0 ; to get rid of bright led
    ; the sparkfun lib has C & C++ & gets tripped up by the "deep+" ldf mode, so we have to point to the .h file directly here, and not use the lib_extra_dirs entry above.
    ; file://lib/downloadLibs/MCU20948/sparkfun_dnload/SparkFunICM20948
    https://github.com/sparkfun/SparkFun_ICM-20948_ArduinoLibrary

; overrode by debug thing above
build_flags = 
; prevent esp32 from crashing when more than 1 ble service setup
    -DCONFIG_BT_NIMBLE_MAX_SERVICES=5
;    -DCONFIG_BT_NIMBLE_MAX_ATTRIBUTES=100
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
; XXXXXXXXXXXXX WARNING INCREASES MEMORY AND COMPILE TIME XXXXXXXXX
; XXXXXXXXXXXXX FOR USING DMP ON ICM-20948 ONLY           XXXXXXXXX
    -D ICM_20948_USE_DMP
    